### ISSUE TITLE
TIYA: Tune Into Your heArt

### ISSUE THREAD

**Issue by shivam-sunita-puri** [brainhackorg/global2024#14]
### Title

Tune into your heart

### Leaders

Rochelle De Silva: rochelled@student.unimelb.edu.au
Shivam Puri: sppuri@student.unimelb.edu.au

### Collaborators

[Dr. Pip Karoly](https://findanexpert.unimelb.edu.au/profile/664387-pip-karoly) 
[Dr. Jodie Naim-Feil Feil](https://findanexpert.unimelb.edu.au/profile/909039-jodie-naim-feil-feil) 
[Dr. Rachel Stirling](https://findanexpert.unimelb.edu.au/profile/878052-rachel-stirling)

### Brainhack Global 2024 Event

Brainhack Aus

### Project Description

The aim of our project is modulating heart rate interoception through music feedback to check if getting in tune with your heart has an impact on your performance in cognitive tasks and emotional state.

The hypothesis for the current experiment is that better cardiac interoception might be positively correlated with task performance and emotion regulation, hence our next step would be training cardiac interoception through music based biofeedback.

The groundbreaking part of our project is that we are testing a new, easily accessible biofeedback - where you get in tune with your heart while listening to music, and the only device you need is your phone and smartwatch. In future we hope that our music based HR feedback allows people to manage their emotions in distress and also help them focus better.

if you are interested, please fill out this Expression of Interest form - https://forms.gle/SmtpUonp23ys3HhH7

For more information, please do visit our GitHub Repository - https://github.com/shivam-sunita-puri/TIYA/tree/main

### Link to project repository/sources

https://github.com/shivam-sunita-puri/TIYA

### Goals for Brainhack Global

Establish correlations between cardiac interoceptions and cognitive task performance and emotional health
Design a musical biofeedback to train people to get in tune with their heart and improve their daily lives

### Good first issues

Heart rate to music 
Develop audio based on resting HR
Convert HR signal to audio stream
Tools: Python
Data: Example HR data provided, participants own data (if wearing Fitbit)

Cognitive tasks
Implement SART, Flanker’s, Posner’s Cueing and subjective scale
Tools: PsychoPy (Pavlovia)

Extension to BrainHack:
Enable real-time streaming and processing of HR data to generate audio
Tools: Fitbit software developer kit (API), web app integration

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/tiya

### Skills

Experimental Designers
Data collection & analysis
Coding (python or other)
App or Game Developers
Music expertise

### What will participants learn?

Extracting, analysing and converting biological signals to audio feedback
Learning experiment designing for biofeedback
Linking physiological data with cognitive performance

### Number of collaborators

more

### Credit to collaborators

Project contributors will be listed in project ReadME and their contributions to the project will be mentioned wherever the project is discussed.

### Image

Leave this text if you don't have an image yet.

### Type

coding_methods, method_development, pipeline_development, other

### Development status

0_concept_no_content

### Topic

hypothesis_testing, physiology

### Tools

Jupyter

### Programming language

Matlab, Python, `R`, html_css, javascript

### Modalities

behavioral, ECG, other

### Git skills

0_no_git_skills

### Anything else?

NA

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [X] Twitter-sized summary of your project pitch.

**Comment by shivam-sunita-puri** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by crnolan** [comment]
Looks good!
