### ISSUE TITLE
MRI based brain thermometry

### ISSUE THREAD

**Issue by AnnaBhlr** [brainhackorg/global2024#17]
### Title

MRI brain thermometry

### Leaders

Christian Behler (@ChristianBehler), Anna Behler (@Anna_Neurosci)

### Brainhack Global 2024 Event

Brainhack Aus

### Project Description

The brain is hot and its thermoregulation underlies different boundary conditions than the body's thermoregulation. Heat in the brain is produced as by-product of metabolism and gets primarily removed by blood flow. In the presence of tumours or neurodegenerative processes this balance can be disturbed. 
MRI can be used to measure brain temperature via spectroscopy or diffusion. The existing analysis pipelines face many problems. That's what this project is going to address. The first aim is to build a model for the calibration of MRS, and test it on real data. Developing code to handle MRS files is also on the to do list. Secondly, we'd like improve the thermometry based on DWI by automated segmentation of the fourth ventricle. It's also planned to explore how machine learning could be used to remove diffusion artefacts. 

### Link to project repository/sources

https://github.com/AnnaBhlr/MRI_BrainThermometry

### Goals for Brainhack Global

- Model for MRS calibration 
- Code/pipeline to handle MRS files
- Automated segmentation of 4th ventricle on diffusion data
- Ideas brainstormed on diffusion artefact removal

### Good first issues

- Could GLMM a good path for model of MRS calibration?
- Which open source data sets could be used to implement automated segmentation? 

### Communication channels

https://mattermost.brainhack.org/brainhack/channels/brainthermometry

### Skills

Newcomer to deep learning pro...each project aim fits a different skill level.

### What will participants learn?

Participants would learn about an overlooked topic and methodology. Coding newbie can start easy with computational modelling and how to handle imaging data.

### Number of collaborators

more

### Credit to collaborators

Project contributors will be acknowledged on project readme and will be listed as co-authors if project eventually ends in a publication.

### Image

<img width="65" alt="Picture 1" src="https://github.com/user-attachments/assets/095a6a8b-66b0-45c7-ace2-69015ca93022">

### Type

coding_methods, data_management, method_development, pipeline_development

### Development status

0_concept_no_content

### Topic

deep_learning, diffusion, MR_methodologies, statistical_modelling, other

### Tools

Brainstorm, other

### Programming language

Python

### Modalities

DWI, other

### Git skills

0_no_git_skills

### Things to do after the project is submitted and ready to review.

- [X] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [ ] Twitter-sized summary of your project pitch.

**Comment by crnolan** [comment]
Hey @AnnaBhlr is this ready to go?

**Comment by AnnaBhlr** [comment]
yes!
