### ISSUE TITLE
Neurodesk: build interactive examples to learn about neuroimaging analysis

### ISSUE THREAD

**Issue by iishiishii** [brainhackorg/global2024#8]
### Title

Neurodesk: build interactive examples to learn about neuroimaging analysis

### Leaders

Thuy Dao (Mattermost @thuy)

### Collaborators

Steffen Bollmann (Mattermost @sbollmann_mri), Andrew Jahn, Monika Doerig

### Brainhack Global 2024 Event

Brainhack Aus

### Project Description

This project aims to build, test, and maintain interactive neuroimaging analysis examples using Jupyter notebooks, GitHub Actions, and Neurodesk. Although resources like Andy’s Brainbook provide excellent learning material, they lack interactivity and can quickly become outdated as software functionalities and parameters evolve, often breaking tutorials.

By leveraging Neurodesk’s containerized environment, we can create reliable, reproducible examples that allow users to explore parameters interactively and build a foundation for their own analyses. These notebooks will also serve as open materials for workshops, facilitating hands-on learning and collaborative projects. Additionally, automating testing with GitHub Actions will ensure examples remain functional and up-to-date.

This project also has potential for community growth: extending the notebook collection through contributions from global Brainhack events would enrich the resource pool with diverse analysis techniques, supporting a broad range of neuroimaging needs.

### Link to project repository/sources

https://github.com/NeuroDesk/example-notebooks

### Goals for Brainhack Global

- Build examples from [Andy's brainbook](https://andysbrainbook.readthedocs.io/en/latest/)

### Good first issues

1. [AFNI_01_DataDownload](https://andysbrainbook.readthedocs.io/en/latest/AFNI/AFNI_Short_Course/AFNI_01_DataDownload.html)

2. [AFNI_04_Preprocessing](https://andysbrainbook.readthedocs.io/en/latest/AFNI/AFNI_Short_Course/AFNI_04_Preprocessing.html)

### Communication channels

[Mattermost](https://mattermost.brainhack.org/brainhack/channels/virtual-neuro-machine-vnm)
[Github Discussion](https://github.com/orgs/NeuroDesk/discussions)

### Skills

- Knowledge of analysis procedures. 
- Bash
- Python

### Onboarding documentation
[README](https://github.com/NeuroDesk/example-notebooks/blob/main/README.md)
[Existing examples](https://www.neurodesk.org/example-notebooks/intro.html#)

### What will participants learn?

- Neurodesk
- Github
- The toolkit they want to document, learn, or share their own pipeline

### Data to use

OpenNeuro or other openly available dataset

### Number of collaborators

2

### Credit to collaborators

Project contributors will be listed in their notebooks and Neurodesk documentation and offered co-authorship in the global OHBM 2025 abstract describing this work.

### Image

Leave this text if you don't have an image yet.

### Type

data_management, pipeline_development, tutorial_recording

### Development status

2_releases_existing

### Topic

connectome, data_visualisation, MR_methodologies, physiology, reproducible_scientific_methods, statistical_modelling, systems_neuroscience, tractography

### Tools

AFNI, ANTs, BIDS, Brainstorm, CPAC, Datalad, FieldTrip, fMRIPrep, Freesurfer, FSL, Jupyter, MNE, MRtrix, Nipype, SPM

### Programming language

Python, shell_scripting, unix_command_line

### Modalities

fMRI, MRI

### Git skills

0_no_git_skills, 1_commit_push

### Things to do after the project is submitted and ready to review.

- [x] Add a comment below the main post of your issue saying: `Hi @brainhackorg/project-monitors my project is ready!`
- [x] Twitter-sized summary of your project pitch.

**Comment by iishiishii** [comment]
Hi @brainhackorg/project-monitors my project is ready!

**Comment by iishiishii** [comment]
Twitter-sized summary:
Building interactive neuroimaging analysis examples with Jupyter, GitHub Actions, and Neurodesk for hands-on learning.

**Comment by crnolan** [comment]
Looks good!
